### ISSUE TITLE
 Is it necessary to use either port  1883 in the native DAB implementation

### ISSUE THREAD

**Issue by xumingxsh** [device-automation-bus/dab-specification-2.0#5]
Hi Team,
    Is it necessary to use either port  1883 in the native DAB implementation or can other ports also be used?
   I found the following description in "DAB-2.0-partner-user-guide":
   In the native DAB implementation, the MQTT broker MUST use the default TCP/IP port 1883 to allow for uniform MQTT connection semantics across different OTT app test infrastructures.

**Comment by GaganBhat** [comment]
Hi @xumingxsh, thank you for reaching out with this question! Apologies for the delayed response.

Yes, we require the use of port 1883 for all partners implementing DAB natively. We're standardizing on this so that DAB protocol users won't have to hard-code port numbers on a per partner basis inside their automation infrastructure.

We also require the use of `mqtt://` as the communication protocol instead of WebSockets / `ws://`. 

Let me know if I can help clarify further on anything.

**Comment by daehyunpark** [comment]
Hi, Gagan Bhat

If a TV manufacturer requires SSL/TLS as a security requirement, it is known that the MQTT SSL/TLS standard port is 8883.
Does DAB 2.0 use SSL/TLS, or are there any plans to use it?
If I use SSL/TLS, which port should I use: 1883 or 8883?

**Comment by GaganBhat** [comment]
@daehyunpark -- DAB implementations will be used in a private local area network for test automation, similar to other automation protocols like DIAL / ADB, and only enabled to app partners. It is highly unlikely that a device with DAB implementation will have its MQTT port-forwarded with a publicly accessible IP.

Given this, and following the model of other automation protocols, DAB will not be using any transport layer encryption (TLS / SSL) at this time. We are standardizing on the `mqtt://` protocol along with port `1833`. We can look deeper into this, so please let us know if there are any specific security concerns that would require the use of TLS / SSL in a test automation environment.

**Comment by GaganBhat** [comment]
Closing the issue for now. Please let me know if this requires more discussion.
